name:                awesome-project-name
version:             0.1.0.0
github:              "githubuser/awesome-project-name"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

dependencies:
- base >= 4.7 && < 5
- servant-server # http server
- aeson # json
- wai # web application (interface)
- warp # web application implementation
- bytestring
- utf8-string
- wai-cors

library:
  source-dirs: src

executables:
  awesome-project-name-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - awesome-project-name
